services:
  app:
    build: .
    container_name: meu-projeto-app
    ports:
      - "3000:3000"

    env_file:
      - ./.env
    environment:
      # Verifique se o seu ficheiro .env está a ser lido
      # ou defina as variáveis aqui.
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=meusecret
      - DB_NAME=meubanco
      - DB_PORT=5432
      # Adicione o seu JWT_SECRET aqui
    
    # Isto força a 'app' a esperar que o 'db'
    # passe no "teste de saúde" antes de ligar.
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: movie-rats-db
    environment:
      # Estas variáveis criam o banco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=meusecret
      - POSTGRES_DB=meubanco
    ports:
      - "5433:5432"
    volumes:
      # Esta linha executa o seu script de tabelas
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # Esta linha guarda os seus dados
      - postgres_data:/var/lib/postgresql/data

    # Este é o "teste de saúde" que verifica se o
    # Postgres está pronto para receber ligações.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meubanco"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: